import type { Metadata } from "next";

import { Container } from "@/components/site/container";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Grainy Palace Financial Service collects, uses and protects your personal data.",
};

export default function PrivacyPage() {
  return (
    <section className="py-16 sm:py-20">
      <Container className="max-w-2xl">
        <p className="eyebrow">Legal</p>
        <h1 className="mt-2 font-heading text-3xl font-semibold sm:text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString("en-GH", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="prose prose-sm mt-8 max-w-none space-y-6 text-foreground/90 sm:prose-base">
          <section>
            <h2 className="font-heading text-lg font-semibold">1. Information we collect</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              When you apply for or use a Grainy Palace product, we collect information you give us
              directly — your name, phone number, Ghana Card number, town, photograph, and account
              activity — as well as information generated by our systems, such as transaction
              records and agent visit logs.
            </p>
          </section>
          <section>
            <h2 className="font-heading text-lg font-semibold">2. How we use it</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              We use your information to open and administer your account, assess loan eligibility,
              comply with Bank of Ghana AML/CFT and know-your-customer requirements, communicate
              with you about your account, and improve our services.
            </p>
          </section>
          <section>
            <h2 className="font-heading text-lg font-semibold">3. Who we share it with</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              We do not sell your personal data. We may share information with regulators (including
              the Bank of Ghana and the Financial Intelligence Centre), credit bureaus, and service
              providers who help us operate (such as our core banking and email providers), under
              confidentiality obligations.
            </p>
          </section>
          <section>
            <h2 className="font-heading text-lg font-semibold">4. Data security</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Client records are held in an access-controlled system with role-based permissions,
              and every account-affecting action is logged. We are registered with the Data
              Protection Commission of Ghana.
            </p>
          </section>
          <section>
            <h2 className="font-heading text-lg font-semibold">5. Your rights</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              You may request access to, correction of, or deletion of your personal data (subject
              to our regulatory record-keeping obligations) by contacting us at{" "}
              <a href={`mailto:${siteConfig.email}`} className="text-gold-700 underline dark:text-gold-500">
                {siteConfig.email}
              </a>.
            </p>
          </section>
          <section>
            <h2 className="font-heading text-lg font-semibold">6. Contact us</h2>
            <p className="mt-2 text-sm text-muted-foreground">{siteConfig.address} · {siteConfig.phoneDisplay}</p>
          </section>
        </div>
      </Container>
    </section>
  );
}
